cd ../src 

# faculty
../../parallel -j10 --resume-failed --results ../Output/faculty_different_Fiedler_layer_num --joblog ../joblog/faculty_different_Fiedler_layer_num CUDA_VISIBLE_DEVICES=7 python ./train.py --Fiedler_layer_num {1} --trainable_alpha --num_trials 10  --hidden 8 --pretrain_with {2} --upset_ratio_coeff {3} --upset_margin_coeff {4}  --imbalance_coeff 0 --dataset {5} --train_with {6} --all_methods all_GNNs -All ::: 3 7 ::: serial_similarity innerproduct dist ::: 1 0 ::: 1 0  ::: faculty_business faculty_cs faculty_history  ::: emb_dist emb_innerproduct

../../parallel -j10 --resume-failed --results ../Output/faculty_different_Fiedler_layer_num_baseline --joblog ../joblog/faculty_different_Fiedler_layer_num_baseline CUDA_VISIBLE_DEVICES=7 python ./train.py --Fiedler_layer_num {1} --trainable_alpha --num_trials 10  --hidden 8 --pretrain_with {2} --upset_ratio_coeff {3} --upset_margin_coeff {4} --imbalance_coeff 0 --train_with emb_baseline --dataset {5} --cluster_rank_baseline {6} --all_methods all_GNNs -All ::: 3 7 ::: serial_similarity innerproduct dist ::: 1 0 ::: 1 0  ::: faculty_business faculty_cs faculty_history  ::: syncRank SpringRank btl serialRank eigenvectorCentrality PageRank SVD_NRS

# animal
../../parallel -j10 --resume-failed --results ../Output/animal_different_Fiedler_layer_num --joblog ../joblog/animal_different_Fiedler_layer_num CUDA_VISIBLE_DEVICES=7 python ./train.py --Fiedler_layer_num {1} --trainable_alpha --num_trials 10  --hidden 4 --pretrain_with {2} --upset_ratio_coeff {3} --upset_margin_coeff {4}  --imbalance_coeff 0 --dataset animal --train_with {5} --all_methods all_GNNs -All ::: 3 7 ::: serial_similarity innerproduct dist ::: 1 0 ::: 1 0   ::: emb_dist emb_innerproduct

../../parallel -j10 --resume-failed --results ../Output/animal_different_Fiedler_layer_num_baseline --joblog ../joblog/animal_different_Fiedler_layer_num_baseline CUDA_VISIBLE_DEVICES=7 python ./train.py --Fiedler_layer_num {1} --trainable_alpha --num_trials 10  --hidden 4 --pretrain_with {2} --upset_ratio_coeff {3} --upset_margin_coeff {4} --imbalance_coeff 0 --train_with emb_baseline --dataset animal --cluster_rank_baseline {5} --all_methods all_GNNs -All ::: 3 7 ::: serial_similarity innerproduct dist ::: 1 0 ::: 1 0   ::: syncRank SpringRank btl serialRank eigenvectorCentrality PageRank SVD_NRS

# football
../../parallel -j10 --resume-failed --results ../Output/football_different_Fiedler_layer_num --joblog ../joblog/football_different_Fiedler_layer_num CUDA_VISIBLE_DEVICES=7 python ./train.py --Fiedler_layer_num {1} --trainable_alpha --num_trials 10  --hidden 4 --pretrain_with {2} --upset_ratio_coeff {3} --upset_margin_coeff {4} --season {5} --imbalance_coeff 0 --dataset {6} --train_with {7} --all_methods all_GNNs -All ::: 3 7 ::: serial_similarity innerproduct dist ::: 1 0 ::: 1 0 ::: {2009..2014}  ::: football finer_football  ::: emb_dist emb_innerproduct

../../parallel -j10 --resume-failed --results ../Output/football_different_Fiedler_layer_num_baseline --joblog ../joblog/football_different_Fiedler_layer_num_baseline CUDA_VISIBLE_DEVICES=7 python ./train.py --Fiedler_layer_num {1} --trainable_alpha --num_trials 10  --hidden 4 --pretrain_with {2} --upset_ratio_coeff {3} --upset_margin_coeff {4} --season {5} --imbalance_coeff 0 --train_with emb_baseline --dataset {6} --cluster_rank_baseline {7} --all_methods all_GNNs -All ::: 3 7 ::: serial_similarity innerproduct dist ::: 1 0 ::: 1 0 ::: {2009..2014}  ::: football finer_football  ::: syncRank SpringRank btl serialRank eigenvectorCentrality PageRank SVD_NRS